# Generated by Django 3.1.7 on 2021-03-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquantity',
            options={'ordering': ('quantity', 'tigID')},
        ),
    ]
