# Generated by Django 3.1.7 on 2021-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoProduct', '0004_auto_20210310_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.FloatField(default=0.0)),
                ('tigID', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('sale', 'tigID'),
            },
        ),
    ]
