# Generated by Django 3.1.7 on 2021-03-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoProduct', '0005_productsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='created',
        ),
    ]
